/* This file was generated by `qmk generate-config-h`. Do not edit or copy.
 */

#pragma once

#ifndef BACKLIGHT_PIN
#   define BACKLIGHT_PIN B7
#endif // BACKLIGHT_PIN

#ifndef DEBOUNCE
#   define DEBOUNCE 5
#endif // DEBOUNCE

#ifndef DEVICE_VER
#   define DEVICE_VER 0x0006
#endif // DEVICE_VER

#ifndef DESCRIPTION
#   define DESCRIPTION planck/rev6_drop
#endif // DESCRIPTION

#ifndef DIODE_DIRECTION
#   define DIODE_DIRECTION COL2ROW
#endif // DIODE_DIRECTION

#ifndef LAYOUT
#   define LAYOUT LAYOUT_ortho_4x12
#endif // LAYOUT

#ifndef LAYOUT_planck_mit
#   define LAYOUT_planck_mit LAYOUT_planck_1x2uC
#endif // LAYOUT_planck_mit

#ifndef LAYOUT_planck_grid
#   define LAYOUT_planck_grid LAYOUT_ortho_4x12
#endif // LAYOUT_planck_grid

#ifndef MANUFACTURER
#   define MANUFACTURER Drop
#endif // MANUFACTURER

#ifndef RGB_DI_PIN
#   define RGB_DI_PIN A1
#endif // RGB_DI_PIN

#ifndef RGBLED_NUM
#   define RGBLED_NUM 9
#endif // RGBLED_NUM

#ifndef PRODUCT
#   define PRODUCT planck/rev6_drop
#endif // PRODUCT

#ifndef PRODUCT_ID
#   define PRODUCT_ID 0xA4F9
#endif // PRODUCT_ID

#ifndef VENDOR_ID
#   define VENDOR_ID 0x03A8
#endif // VENDOR_ID

#ifndef QMK_ESC_OUTPUT
#   define QMK_ESC_OUTPUT F1
#endif // QMK_ESC_OUTPUT

#ifndef QMK_ESC_INPUT
#   define QMK_ESC_INPUT D5
#endif // QMK_ESC_INPUT

#ifndef QMK_LED
#   define QMK_LED E6
#endif // QMK_LED

#ifndef QMK_SPEAKER
#   define QMK_SPEAKER C6
#endif // QMK_SPEAKER

#ifndef MATRIX_COLS
#   define MATRIX_COLS 6
#endif // MATRIX_COLS

#ifndef MATRIX_COL_PINS
#   define MATRIX_COL_PINS { B11, B10, B2, B1, A7, B0 }
#endif // MATRIX_COL_PINS


#ifndef MATRIX_ROWS
#   define MATRIX_ROWS 8
#endif // MATRIX_ROWS

#ifndef MATRIX_ROW_PINS
#   define MATRIX_ROW_PINS { A10, A9, A8, B15, C13, C14, C15, A2 }
#endif // MATRIX_ROW_PINS
