# This file was generated by `qmk generate-rules-mk`. Do not edit or copy.

BOOTLOADER ?= stm32-dfu
LAYOUTS ?= ortho_4x12 planck_mit
MCU ?= STM32F303
MOUSEKEY_ENABLE ?= on
BOOTMAGIC_ENABLE ?= yes
MOUSEKEY_ENABLE ?= yes
EXTRAKEY_ENABLE ?= yes
CONSOLE_ENABLE ?= yes
COMMAND_ENABLE ?= yes
SLEEP_LED_ENABLE ?= no
NKRO_ENABLE ?= yes
BACKLIGHT_ENABLE ?= no
RGBLIGHT_ENABLE ?= yes
AUDIO_ENABLE ?= yes
RGB_MATRIX_ENABLE ?= no
ENCODER_ENABLE ?= yes
DIP_SWITCH_ENABLE ?= yes
