/* This file was generated by `qmk generate-config-h`. Do not edit or copy.
 */

#pragma once

#ifndef DEBOUNCE
#   define DEBOUNCE 5
#endif // DEBOUNCE

#ifndef DEVICE_VER
#   define DEVICE_VER 0x0001
#endif // DEVICE_VER

#ifndef DESCRIPTION
#   define DESCRIPTION sofle/rev1
#endif // DESCRIPTION

#ifndef DIODE_DIRECTION
#   define DIODE_DIRECTION COL2ROW
#endif // DIODE_DIRECTION

#ifndef MANUFACTURER
#   define MANUFACTURER JosefAdamcik
#endif // MANUFACTURER

#ifndef PRODUCT
#   define PRODUCT sofle/rev1
#endif // PRODUCT

#ifndef PRODUCT_ID
#   define PRODUCT_ID 0x0287
#endif // PRODUCT_ID

#ifndef VENDOR_ID
#   define VENDOR_ID 0xFC32
#endif // VENDOR_ID

#ifndef SOFT_SERIAL_PIN
#   define SOFT_SERIAL_PIN D2
#endif // SOFT_SERIAL_PIN

#ifndef TAP_CODE_DELAY
#   define TAP_CODE_DELAY 10
#endif // TAP_CODE_DELAY

#ifndef TAPPING_TERM
#   define TAPPING_TERM 100
#endif // TAPPING_TERM

#ifndef MATRIX_COLS
#   define MATRIX_COLS 6
#endif // MATRIX_COLS

#ifndef MATRIX_COL_PINS
#   define MATRIX_COL_PINS { F6, F7, B1, B3, B2, B6 }
#endif // MATRIX_COL_PINS


#ifndef MATRIX_ROWS
#   define MATRIX_ROWS 5
#endif // MATRIX_ROWS

#ifndef MATRIX_ROW_PINS
#   define MATRIX_ROW_PINS { C6, D7, E6, B4, B5 }
#endif // MATRIX_ROW_PINS
