# This file was generated by `qmk generate-rules-mk`. Do not edit or copy.

BOOTLOADER ?= caterina
MCU ?= atmega32u4
SPLIT_KEYBOARD ?= on
ENCODER_ENABLE ?= yes
OLED_ENABLE ?= yes
SWAP_HANDS_ENABLE ?= yes
