# This file was generated by `qmk generate-rules-mk`. Do not edit or copy.

BOARD ?= QMK_PROTON_C
BOOTLOADER ?= stm32-dfu
LAYOUTS ?= ortho_4x12 planck_mit
MCU ?= STM32F303
MOUSEKEY_ENABLE ?= on
MOUSEKEY_ENABLE ?= yes
EXTRAKEY_ENABLE ?= yes
CONSOLE_ENABLE ?= yes
COMMAND_ENABLE ?= yes
NKRO_ENABLE ?= yes
BACKLIGHT_ENABLE ?= no
AUDIO_ENABLE ?= yes
RGBLIGHT_ENABLE ?= yes
SLEEP_LED_ENABLE ?= no
RGB_MATRIX_ENABLE ?= no
ENCODER_ENABLE ?= yes
DIP_SWITCH_ENABLE ?= yes
BOOTMAGIC_ENABLE ?= lite
