/* This file was generated by `qmk generate-layouts`. Do not edit or copy.
 */

#pragma once

#ifndef LAYOUT
#   define LAYOUT LAYOUT_ortho_4x12
#endif

#ifndef LAYOUT_planck_mit
#   define LAYOUT_planck_mit LAYOUT_planck_1x2uC
#endif

#ifndef LAYOUT_planck_grid
#   define LAYOUT_planck_grid LAYOUT_ortho_4x12
#endif
